### ISSUE TITLE
Compile with TypeScript 2.5

### ISSUE THREAD

**Issue by alexeagle** [angular/tsickle#611]
```

294   ts.setEmitFlags(node, (ts.getEmitFlags(node) || 0) | ts.EmitFlags.NoComments);
                                ~~~~~~~~~~~~

/tsickle/src/transformer_util.ts(294,29): error TS2551: Property 'getEmitFlags' does not exist on type 'typeof ts'. Did you mean 'setEmitFlags'?

309     node = ts.updateProperty(
               ~~~~~~~~~~~~~~~~~~
310                pd, pd.decorators, pd.modifiers, resetTextRange(pd.name) as ts.PropertyName, pd.type,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
311                pd.initializer!) as ts.Node as T;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/tsickle/src/transformer_util.ts(309,12): error TS2554: Expected 7 arguments, but got 6.

400       statements.unshift(leading.commentStmt);
                     ~~~~~~~

/tsickle/src/transformer_util.ts(400,18): error TS2339: Property 'unshift' does not exist on type 'NodeArray<Statement>'.

403       statements.push(trailing.commentStmt);
                     ~~~~

/tsickle/src/transformer_util.ts(403,18): error TS2339: Property 'push' does not exist on type 'NodeArray<Statement>'.

682             exportedSymbols = this.getNamedSymbols(exportDecl.exportClause.elements);
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/tsickle/src/tsickle.ts(682,52): error TS2345: Argument of type 'NodeArray<ExportSpecifier>' is not assignable to parameter of type '(ImportSpecifier | ExportSpecifier)[]'.
  Property 'push' is missing in type 'NodeArray<ExportSpecifier>'.

1050       if (moduleExports.has(name)) {
               ~~~~~~~~~~~~~~~~~~~~~~~

/tsickle/src/tsickle.ts(1050,11): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type '((key: __String) => boolean) | ((key: string) => boolean)' has no compatible call signatures.

1176           symbols = this.getNamedSymbols(importClause.namedBindings.elements);
                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/tsickle/src/tsickle.ts(1176,42): error TS2345: Argument of type 'NodeArray<ImportSpecifier>' is not assignable to parameter of type '(ImportSpecifier | ExportSpecifier)[]'.
  Property 'push' is missing in type 'NodeArray<ImportSpecifier>'.

110     ts.SymbolFlags.ExportType,
                       ~~~~~~~~~~

/tsickle/src/type-translator.ts(110,20): error TS2339: Property 'ExportType' does not exist on type 'typeof SymbolFlags'.

111     ts.SymbolFlags.ExportNamespace,
                       ~~~~~~~~~~~~~~~

/tsickle/src/type-translator.ts(111,20): error TS2339: Property 'ExportNamespace' does not exist on type 'typeof SymbolFlags'.
```

**Comment by rkirov** [comment]
See #627
