### ISSUE TITLE
package.json from npm appears to point to the wrong source directory

### ISSUE THREAD

**Issue by BrianLeishman** [angular/tsickle#1272]
I was trying to get the demo to compile with TS 4.3, but I kept getting stuck with this error trying to `import * as tsickle from "tsickle";`

> Cannot find module 'tsickle' or its corresponding type declarations.

Seems like `typings` and `main` are set incorrect, or at least they don't match what actually gets installed by npm. Making the following changes seems to make everything happy.

```diff
{
  ... 
-  "main": "src/tsickle.js",
+  "main": "build/src/tsickle.js",
  ...
-  "typings": "src/tsickle.d.ts",
+  "typings": "build/src/tsickle.d.ts",
  "version": "0.40.0"
}
```

**Comment by mprobst** [comment]
You're right @BrianLeishman, that's an oversight.

Do you care to send a CL to fix?

**Comment by BrianLeishman** [comment]
A CL?

**Comment by BrianLeishman** [comment]
Something else I'm not sure about, but in the master branch the package json looks like this

```json
{
  "main": "out/src/tsickle.js",
  "typings": "out/src/tsickle.d.ts",
}
```

Which doesn't look like the one coming from npm but still isn't right? Should "out" be changed to "build"?

**Comment by mprobst** [comment]
@BrianLeishman sorry, I meant a Pull Request (CL is Google-internal lingo). With the current setup, the compiler emits to `./out`, so I think that's correct.

**Comment by BrianLeishman** [comment]
Does this mean the npm package just needs republished? The package.json typescript version also doesn't match the current master version, so it could just be out of date?

**Comment by mprobst** [comment]
@BrianLeishman not quite, see PR #1273. I also had to bump the version required, and while I was at it, included the demo build in our CI, so this hopefully won't break again.

**Comment by mprobst** [comment]
There is a published 0.41.0 now though which you should be able to depend on.
